### PR TITLE
ci: fix workflow dispatch typo build action trigger

### PR DESCRIPTION
**Pull request by jssotomdz**

### CODE REVIEW

**Comment by jssotomdz** [comment]
@sergio-costas need a review here, not sure why I don't have access to the repo

**Review by sergio-costas — APPROVED** [review]
Looks sensible.

**Comment by sergio-costas** [comment]
Mmm... neither do I... I can't merge this.

**Comment by jssotomdz** [comment]
@seb128 do you have permissions to merge this?

**Review by seb128 — APPROVED** [review]
Thanks

**Comment by seb128** [comment]
desktop-team wasn't set as maintainer on that snap, I've also fixed that so you should have access now

**Pull request merged**
