### PR TITLE
Initial updates for base and extension

### PR DESCRIPTION
**Pull request by hellsworth**

### CODE REVIEW

**Comment by hellsworth** [comment]
There's currently a build failure I'm stumped on:
```
Configuring org.gnome.Dictionary.appdata.xml.in using configuration                   
                                                                                      
../src/data/appdata/meson.build:3:5: ERROR: Function does not take positional arguments.                                                                                     
                                                                                      
A full log can be found at /root/parts/gnome-dictionary/build/meson-logs/meson-log.txt                                                                                       
Failed to build 'gnome-dictionary'.                                                   
                                                                                      
Recommended resolution:                                                               
Check the build logs and ensure the part's configuration and sources are correct.
```

[here is the meson.build file line 5](https://gitlab.gnome.org/GNOME/gnome-dictionary/-/blob/40.0/meson.build#L5) so maybe we need a newer compiler to allow positional arguments?? @kenvandine thoughts?

**Comment by seb128** [comment]
the build error is due to a misuse of meson which was accepted b older versions but turned into an error now, we workaround it in other snaps by setting 'meson-version: 0.58.1' as in https://bazaar.launchpad.net/~desktop-snappers/gnome-calendar/snap/revision/35

details on https://github.com/mesonbuild/meson/issues/9441

**Comment by hellsworth** [comment]
Thanks @seb128  so much for the guidance!!!

**Comment by hellsworth** [comment]
@seb128 when we pin the meson version (I've tried with several different meson versions in local builds, all with the same result), we see many of these errors:
```
/snap/gnome-3-38-2004-sdk/current/usr/include/stdio.h:456:24: error: redundant redeclaration of ‘vscanf’ [-Werror=redundant-decls]
  456 | extern int __REDIRECT (vscanf, (const char *__restrict __format,
      |
```
@seb128 what do you think of this? It looks like maybe a gcc version problem but debugging that and building the right custom gcc as part of gnome-dictionary seems like overkill...

**Comment by seb128** [comment]
@kenvandine hit similar issue with the sdk snaps build before, that's weird. The meson issue has been fixed in https://gitlab.gnome.org/GNOME/gnome-dictionary/-/commit/cf3f8a67c , could you try to remove the meson version and build from master instead?

**Comment by hellsworth** [comment]
As a note, yesterday I tried master but also with the pin'd version of meson at 0.61.0, and hit this same issue.

**Comment by hellsworth** [comment]
> could you try to remove the meson version and build from master instead?

Even with meson not-pin'd, and building gnome-dictionary from upstream's master branch (pushed this change to my branch so you can see exactly what i'm building), still gives the same build failure.

**Comment by kenvandine** [comment]
I suspect the root cause of the redundant declarations issue lies in either the SDK snap or the extension.  We should try to figure that out, buts work around it to help get everything to core22.

**Pull request merged**
